### ISSUE TITLE
Thumb not shown in public view

### ISSUE THREAD

**Issue by Falteri** [ives1227/myomekaplugins#1]
It seems that the plugin has some problem showing image thumbnail in the public view.
It seems that it is not able to show thumb unless one insert the linkto parameter.

**Comment by doana** [comment]
I ran into this as well. It seems to be intentional, although I don't understand why. 

Looking at [the code,](https://github.com/ives1227/myomekaplugins/blob/master/DigitalObjectLinker/DigitalObjectLinkerPlugin.php#L152) it seems to hide the element unless something that is not an image is included in one of the relation elements. So, it doesn't necessarily have to include the linkto parameter. Any text string will cause the image to render. 

If you want, remove that function and remove `'display_elements'` from the [filter array](https://github.com/ives1227/myomekaplugins/blob/master/DigitalObjectLinker/DigitalObjectLinkerPlugin.php#L44) and it should always display the image.

**Comment by Falteri** [comment]
Many thanks for your usefull reply!
Me too I think that there are no celar reason for this behaviour.
Anyway I think I'll follow your suggestion about changing the code.
Ciao!

Inviato da iPhone

**Comment by ives1227** [comment]
Yes, you are correct that it was suppressing the images.  We were purposely suppressing it from the 'relation' area in our version because we chose to display the images in a different way on the item 'show' pages.  Since this release, we have coded it into our custom theme so this suppression is no longer necessary.  I will make sure to update this asap.  Thanks for the fix doana.

**Comment by ives1227** [comment]
Fix is in dol_release_2_0_1.  Closing.
